-- ============================================================
-- START CREW — Migration 010: Task-Namen auf Deutsch
--
-- Uebersetzt die englischen task_name-Eintraege aus Migration 002
-- in deutsche Aequivalente (Kurs-Anforderung: Deutsches UI).
-- Betrifft tasks.task_name, tasks.depends_on, historical_staffing.
-- Idempotent: zweiter Lauf aendert keine Zeilen mehr.
-- ============================================================

-- 1) task_name in tasks: direkte 1:1-Uebersetzung.
UPDATE tasks SET task_name = 'Material vom Campus transportieren' WHERE task_name = 'Transport things from campus';
UPDATE tasks SET task_name = 'Material zum Campus transportieren' WHERE task_name = 'Transport things to campus';
UPDATE tasks SET task_name = 'Container anliefern' WHERE task_name = 'Get containers Delivered';
UPDATE tasks SET task_name = 'Autos für Speaker vorbereiten' WHERE task_name = 'Set up cars for speakers';
UPDATE tasks SET task_name = 'Screens & Speaker aufhängen' WHERE task_name = 'Hang screens & speakers';
UPDATE tasks SET task_name = 'Stakeholder-Betreuung' WHERE task_name = 'Stakeholders management';
UPDATE tasks SET task_name = 'Traverse tief abbauen' WHERE task_name = 'Take down traverse low';
UPDATE tasks SET task_name = 'Licht & Kabel entfernen' WHERE task_name = 'Remove lights & cables';
UPDATE tasks SET task_name = 'Traversen demontieren' WHERE task_name = 'Dissassemble traversen';
UPDATE tasks SET task_name = 'Material zum Campus zurück' WHERE task_name = 'Return stuff to campus';
UPDATE tasks SET task_name = 'Sound-Check' WHERE task_name = 'Test Sound and Audio';
UPDATE tasks SET task_name = 'Beschilderung abbauen' WHERE task_name = 'Take down printables';
UPDATE tasks SET task_name = 'Kaffee-Points bauen' WHERE task_name = 'Build Coffee points';
UPDATE tasks SET task_name = 'Holz in die Halle bringen' WHERE task_name = 'Move wood into hall';
UPDATE tasks SET task_name = 'Sicherheits-Endcheck' WHERE task_name = 'Final Saftey checks';
UPDATE tasks SET task_name = 'Möbel abbauen' WHERE task_name = 'Take down furniture';
UPDATE tasks SET task_name = 'Traverse hoch hängen' WHERE task_name = 'Hang Traverse High';
UPDATE tasks SET task_name = 'Traverse aufbauen' WHERE task_name = 'Assemble Traverse';
UPDATE tasks SET task_name = 'Traverse tief hängen' WHERE task_name = 'Hang Traverse Low';
UPDATE tasks SET task_name = 'Gerüst bauen' WHERE task_name = 'Build scaffolding';
UPDATE tasks SET task_name = 'LKWs entladen' WHERE task_name = 'Unloading Trucks';
UPDATE tasks SET task_name = 'Kabel verlegen' WHERE task_name = 'Cable management';
UPDATE tasks SET task_name = 'Show-Tag-Start' WHERE task_name = 'Start of showday';
UPDATE tasks SET task_name = 'Motoren abbauen' WHERE task_name = 'Take down motors';
UPDATE tasks SET task_name = 'Beschilderung anbringen' WHERE task_name = 'Hang printables';
UPDATE tasks SET task_name = 'Container beladen' WHERE task_name = 'Load containers';
UPDATE tasks SET task_name = 'Autos zurückfahren' WHERE task_name = 'Drive cars back';
UPDATE tasks SET task_name = 'Event-Start' WHERE task_name = 'Start of event';
UPDATE tasks SET task_name = 'Lager aufbauen' WHERE task_name = 'Assemble Lager';
UPDATE tasks SET task_name = 'Service-Points' WHERE task_name = 'Service points';
UPDATE tasks SET task_name = 'Bühnen-Sessions' WHERE task_name = 'Stage Sessions';
UPDATE tasks SET task_name = 'Show-Tag-Ende' WHERE task_name = 'End of Showday';
UPDATE tasks SET task_name = 'Holz abbauen' WHERE task_name = 'Take down wood';
UPDATE tasks SET task_name = 'Möbel aufstellen' WHERE task_name = 'Add Furniture';
UPDATE tasks SET task_name = 'Booths bauen' WHERE task_name = 'Build Booths';
UPDATE tasks SET task_name = 'Visuals testen' WHERE task_name = 'Test Visuals';
UPDATE tasks SET task_name = 'Event-Ende' WHERE task_name = 'End of event';
UPDATE tasks SET task_name = 'Motoren aufhängen' WHERE task_name = 'Hang motors';
UPDATE tasks SET task_name = 'LKWs beladen' WHERE task_name = 'Load trucks';
UPDATE tasks SET task_name = 'Kisten sortieren' WHERE task_name = 'Sort boxes';
UPDATE tasks SET task_name = 'Licht installieren' WHERE task_name = 'Rig lights';
UPDATE tasks SET task_name = 'Autos mieten' WHERE task_name = 'Rent cars';
UPDATE tasks SET task_name = 'Holz vorbereiten' WHERE task_name = 'Prep Wood';
UPDATE tasks SET task_name = 'Holz zuschneiden' WHERE task_name = 'Cut wood';
UPDATE tasks SET task_name = 'Fahrdienst' WHERE task_name = 'Driving';

-- 2) depends_on in tasks: REPLACE, da depends_on mehrere Task-Namen
--    per ' + ' verkettet enthaelt. Reihenfolge nach Laenge absteigend.
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Transport things from campus', 'Material vom Campus transportieren') WHERE depends_on LIKE '%Transport things from campus%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Transport things to campus', 'Material zum Campus transportieren') WHERE depends_on LIKE '%Transport things to campus%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Get containers Delivered', 'Container anliefern') WHERE depends_on LIKE '%Get containers Delivered%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Set up cars for speakers', 'Autos für Speaker vorbereiten') WHERE depends_on LIKE '%Set up cars for speakers%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Hang screens & speakers', 'Screens & Speaker aufhängen') WHERE depends_on LIKE '%Hang screens & speakers%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Stakeholders management', 'Stakeholder-Betreuung') WHERE depends_on LIKE '%Stakeholders management%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Take down traverse low', 'Traverse tief abbauen') WHERE depends_on LIKE '%Take down traverse low%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Remove lights & cables', 'Licht & Kabel entfernen') WHERE depends_on LIKE '%Remove lights & cables%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Dissassemble traversen', 'Traversen demontieren') WHERE depends_on LIKE '%Dissassemble traversen%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Return stuff to campus', 'Material zum Campus zurück') WHERE depends_on LIKE '%Return stuff to campus%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Test Sound and Audio', 'Sound-Check') WHERE depends_on LIKE '%Test Sound and Audio%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Take down printables', 'Beschilderung abbauen') WHERE depends_on LIKE '%Take down printables%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Build Coffee points', 'Kaffee-Points bauen') WHERE depends_on LIKE '%Build Coffee points%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Move wood into hall', 'Holz in die Halle bringen') WHERE depends_on LIKE '%Move wood into hall%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Final Saftey checks', 'Sicherheits-Endcheck') WHERE depends_on LIKE '%Final Saftey checks%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Take down furniture', 'Möbel abbauen') WHERE depends_on LIKE '%Take down furniture%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Hang Traverse High', 'Traverse hoch hängen') WHERE depends_on LIKE '%Hang Traverse High%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Assemble Traverse', 'Traverse aufbauen') WHERE depends_on LIKE '%Assemble Traverse%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Hang Traverse Low', 'Traverse tief hängen') WHERE depends_on LIKE '%Hang Traverse Low%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Build scaffolding', 'Gerüst bauen') WHERE depends_on LIKE '%Build scaffolding%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Unloading Trucks', 'LKWs entladen') WHERE depends_on LIKE '%Unloading Trucks%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Cable management', 'Kabel verlegen') WHERE depends_on LIKE '%Cable management%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Start of showday', 'Show-Tag-Start') WHERE depends_on LIKE '%Start of showday%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Take down motors', 'Motoren abbauen') WHERE depends_on LIKE '%Take down motors%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Hang printables', 'Beschilderung anbringen') WHERE depends_on LIKE '%Hang printables%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Load containers', 'Container beladen') WHERE depends_on LIKE '%Load containers%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Drive cars back', 'Autos zurückfahren') WHERE depends_on LIKE '%Drive cars back%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Start of event', 'Event-Start') WHERE depends_on LIKE '%Start of event%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Assemble Lager', 'Lager aufbauen') WHERE depends_on LIKE '%Assemble Lager%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Service points', 'Service-Points') WHERE depends_on LIKE '%Service points%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Stage Sessions', 'Bühnen-Sessions') WHERE depends_on LIKE '%Stage Sessions%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'End of Showday', 'Show-Tag-Ende') WHERE depends_on LIKE '%End of Showday%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Take down wood', 'Holz abbauen') WHERE depends_on LIKE '%Take down wood%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Add Furniture', 'Möbel aufstellen') WHERE depends_on LIKE '%Add Furniture%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Build Booths', 'Booths bauen') WHERE depends_on LIKE '%Build Booths%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Test Visuals', 'Visuals testen') WHERE depends_on LIKE '%Test Visuals%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'End of event', 'Event-Ende') WHERE depends_on LIKE '%End of event%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Hang motors', 'Motoren aufhängen') WHERE depends_on LIKE '%Hang motors%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Load trucks', 'LKWs beladen') WHERE depends_on LIKE '%Load trucks%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Sort boxes', 'Kisten sortieren') WHERE depends_on LIKE '%Sort boxes%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Rig lights', 'Licht installieren') WHERE depends_on LIKE '%Rig lights%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Rent cars', 'Autos mieten') WHERE depends_on LIKE '%Rent cars%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Prep Wood', 'Holz vorbereiten') WHERE depends_on LIKE '%Prep Wood%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Cut wood', 'Holz zuschneiden') WHERE depends_on LIKE '%Cut wood%';
UPDATE tasks SET depends_on = REPLACE(depends_on, 'Driving', 'Fahrdienst') WHERE depends_on LIKE '%Driving%';

-- 3) task_name in historical_staffing (2024/2025 ML-Trainingsdaten).
UPDATE historical_staffing SET task_name = 'Material vom Campus transportieren' WHERE task_name = 'Transport things from campus';
UPDATE historical_staffing SET task_name = 'Material zum Campus transportieren' WHERE task_name = 'Transport things to campus';
UPDATE historical_staffing SET task_name = 'Container anliefern' WHERE task_name = 'Get containers Delivered';
UPDATE historical_staffing SET task_name = 'Autos für Speaker vorbereiten' WHERE task_name = 'Set up cars for speakers';
UPDATE historical_staffing SET task_name = 'Screens & Speaker aufhängen' WHERE task_name = 'Hang screens & speakers';
UPDATE historical_staffing SET task_name = 'Stakeholder-Betreuung' WHERE task_name = 'Stakeholders management';
UPDATE historical_staffing SET task_name = 'Traverse tief abbauen' WHERE task_name = 'Take down traverse low';
UPDATE historical_staffing SET task_name = 'Licht & Kabel entfernen' WHERE task_name = 'Remove lights & cables';
UPDATE historical_staffing SET task_name = 'Traversen demontieren' WHERE task_name = 'Dissassemble traversen';
UPDATE historical_staffing SET task_name = 'Material zum Campus zurück' WHERE task_name = 'Return stuff to campus';
UPDATE historical_staffing SET task_name = 'Sound-Check' WHERE task_name = 'Test Sound and Audio';
UPDATE historical_staffing SET task_name = 'Beschilderung abbauen' WHERE task_name = 'Take down printables';
UPDATE historical_staffing SET task_name = 'Kaffee-Points bauen' WHERE task_name = 'Build Coffee points';
UPDATE historical_staffing SET task_name = 'Holz in die Halle bringen' WHERE task_name = 'Move wood into hall';
UPDATE historical_staffing SET task_name = 'Sicherheits-Endcheck' WHERE task_name = 'Final Saftey checks';
UPDATE historical_staffing SET task_name = 'Möbel abbauen' WHERE task_name = 'Take down furniture';
UPDATE historical_staffing SET task_name = 'Traverse hoch hängen' WHERE task_name = 'Hang Traverse High';
UPDATE historical_staffing SET task_name = 'Traverse aufbauen' WHERE task_name = 'Assemble Traverse';
UPDATE historical_staffing SET task_name = 'Traverse tief hängen' WHERE task_name = 'Hang Traverse Low';
UPDATE historical_staffing SET task_name = 'Gerüst bauen' WHERE task_name = 'Build scaffolding';
UPDATE historical_staffing SET task_name = 'LKWs entladen' WHERE task_name = 'Unloading Trucks';
UPDATE historical_staffing SET task_name = 'Kabel verlegen' WHERE task_name = 'Cable management';
UPDATE historical_staffing SET task_name = 'Show-Tag-Start' WHERE task_name = 'Start of showday';
UPDATE historical_staffing SET task_name = 'Motoren abbauen' WHERE task_name = 'Take down motors';
UPDATE historical_staffing SET task_name = 'Beschilderung anbringen' WHERE task_name = 'Hang printables';
UPDATE historical_staffing SET task_name = 'Container beladen' WHERE task_name = 'Load containers';
UPDATE historical_staffing SET task_name = 'Autos zurückfahren' WHERE task_name = 'Drive cars back';
UPDATE historical_staffing SET task_name = 'Event-Start' WHERE task_name = 'Start of event';
UPDATE historical_staffing SET task_name = 'Lager aufbauen' WHERE task_name = 'Assemble Lager';
UPDATE historical_staffing SET task_name = 'Service-Points' WHERE task_name = 'Service points';
UPDATE historical_staffing SET task_name = 'Bühnen-Sessions' WHERE task_name = 'Stage Sessions';
UPDATE historical_staffing SET task_name = 'Show-Tag-Ende' WHERE task_name = 'End of Showday';
UPDATE historical_staffing SET task_name = 'Holz abbauen' WHERE task_name = 'Take down wood';
UPDATE historical_staffing SET task_name = 'Möbel aufstellen' WHERE task_name = 'Add Furniture';
UPDATE historical_staffing SET task_name = 'Booths bauen' WHERE task_name = 'Build Booths';
UPDATE historical_staffing SET task_name = 'Visuals testen' WHERE task_name = 'Test Visuals';
UPDATE historical_staffing SET task_name = 'Event-Ende' WHERE task_name = 'End of event';
UPDATE historical_staffing SET task_name = 'Motoren aufhängen' WHERE task_name = 'Hang motors';
UPDATE historical_staffing SET task_name = 'LKWs beladen' WHERE task_name = 'Load trucks';
UPDATE historical_staffing SET task_name = 'Kisten sortieren' WHERE task_name = 'Sort boxes';
UPDATE historical_staffing SET task_name = 'Licht installieren' WHERE task_name = 'Rig lights';
UPDATE historical_staffing SET task_name = 'Autos mieten' WHERE task_name = 'Rent cars';
UPDATE historical_staffing SET task_name = 'Holz vorbereiten' WHERE task_name = 'Prep Wood';
UPDATE historical_staffing SET task_name = 'Holz zuschneiden' WHERE task_name = 'Cut wood';
UPDATE historical_staffing SET task_name = 'Fahrdienst' WHERE task_name = 'Driving';

-- 4) depends_on in historical_staffing.
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Transport things from campus', 'Material vom Campus transportieren') WHERE depends_on LIKE '%Transport things from campus%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Transport things to campus', 'Material zum Campus transportieren') WHERE depends_on LIKE '%Transport things to campus%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Get containers Delivered', 'Container anliefern') WHERE depends_on LIKE '%Get containers Delivered%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Set up cars for speakers', 'Autos für Speaker vorbereiten') WHERE depends_on LIKE '%Set up cars for speakers%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Hang screens & speakers', 'Screens & Speaker aufhängen') WHERE depends_on LIKE '%Hang screens & speakers%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Stakeholders management', 'Stakeholder-Betreuung') WHERE depends_on LIKE '%Stakeholders management%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Take down traverse low', 'Traverse tief abbauen') WHERE depends_on LIKE '%Take down traverse low%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Remove lights & cables', 'Licht & Kabel entfernen') WHERE depends_on LIKE '%Remove lights & cables%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Dissassemble traversen', 'Traversen demontieren') WHERE depends_on LIKE '%Dissassemble traversen%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Return stuff to campus', 'Material zum Campus zurück') WHERE depends_on LIKE '%Return stuff to campus%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Test Sound and Audio', 'Sound-Check') WHERE depends_on LIKE '%Test Sound and Audio%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Take down printables', 'Beschilderung abbauen') WHERE depends_on LIKE '%Take down printables%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Build Coffee points', 'Kaffee-Points bauen') WHERE depends_on LIKE '%Build Coffee points%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Move wood into hall', 'Holz in die Halle bringen') WHERE depends_on LIKE '%Move wood into hall%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Final Saftey checks', 'Sicherheits-Endcheck') WHERE depends_on LIKE '%Final Saftey checks%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Take down furniture', 'Möbel abbauen') WHERE depends_on LIKE '%Take down furniture%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Hang Traverse High', 'Traverse hoch hängen') WHERE depends_on LIKE '%Hang Traverse High%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Assemble Traverse', 'Traverse aufbauen') WHERE depends_on LIKE '%Assemble Traverse%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Hang Traverse Low', 'Traverse tief hängen') WHERE depends_on LIKE '%Hang Traverse Low%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Build scaffolding', 'Gerüst bauen') WHERE depends_on LIKE '%Build scaffolding%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Unloading Trucks', 'LKWs entladen') WHERE depends_on LIKE '%Unloading Trucks%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Cable management', 'Kabel verlegen') WHERE depends_on LIKE '%Cable management%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Start of showday', 'Show-Tag-Start') WHERE depends_on LIKE '%Start of showday%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Take down motors', 'Motoren abbauen') WHERE depends_on LIKE '%Take down motors%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Hang printables', 'Beschilderung anbringen') WHERE depends_on LIKE '%Hang printables%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Load containers', 'Container beladen') WHERE depends_on LIKE '%Load containers%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Drive cars back', 'Autos zurückfahren') WHERE depends_on LIKE '%Drive cars back%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Start of event', 'Event-Start') WHERE depends_on LIKE '%Start of event%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Assemble Lager', 'Lager aufbauen') WHERE depends_on LIKE '%Assemble Lager%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Service points', 'Service-Points') WHERE depends_on LIKE '%Service points%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Stage Sessions', 'Bühnen-Sessions') WHERE depends_on LIKE '%Stage Sessions%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'End of Showday', 'Show-Tag-Ende') WHERE depends_on LIKE '%End of Showday%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Take down wood', 'Holz abbauen') WHERE depends_on LIKE '%Take down wood%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Add Furniture', 'Möbel aufstellen') WHERE depends_on LIKE '%Add Furniture%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Build Booths', 'Booths bauen') WHERE depends_on LIKE '%Build Booths%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Test Visuals', 'Visuals testen') WHERE depends_on LIKE '%Test Visuals%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'End of event', 'Event-Ende') WHERE depends_on LIKE '%End of event%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Hang motors', 'Motoren aufhängen') WHERE depends_on LIKE '%Hang motors%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Load trucks', 'LKWs beladen') WHERE depends_on LIKE '%Load trucks%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Sort boxes', 'Kisten sortieren') WHERE depends_on LIKE '%Sort boxes%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Rig lights', 'Licht installieren') WHERE depends_on LIKE '%Rig lights%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Rent cars', 'Autos mieten') WHERE depends_on LIKE '%Rent cars%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Prep Wood', 'Holz vorbereiten') WHERE depends_on LIKE '%Prep Wood%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Cut wood', 'Holz zuschneiden') WHERE depends_on LIKE '%Cut wood%';
UPDATE historical_staffing SET depends_on = REPLACE(depends_on, 'Driving', 'Fahrdienst') WHERE depends_on LIKE '%Driving%';
